# Generated by Django 5.1.3 on 2025-01-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_parent_productimage_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
